// <auto-generated />
using System;
using FlightDocSys.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightDocSys.Migrations
{
    [DbContext(typeof(FlightDocSysContext))]
    [Migration("20231205045032_DBinit")]
    partial class DBinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FlightDocSys.Models.Entities.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentID");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Document_TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeDoID");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("FlightID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,1)")
                        .HasDefaultValueSql("((1.0))");

                    b.HasKey("DocumentId");

                    b.HasIndex("Document_TypeId");

                    b.HasIndex("FlightId");

                    b.ToTable("DOCUMENT", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Document_Type", b =>
                {
                    b.Property<int>("Document_TypeId")
                        .HasColumnType("int")
                        .HasColumnName("Document_TypeId");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Document_TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("DOCUMENT_TYPE", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("FlightID");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RouteID");

                    b.HasKey("FlightId");

                    b.HasIndex("RouteId");

                    b.ToTable("FLIGHT", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("GroupId");

                    b.ToTable("GROUP", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PermissionId");

                    b.ToTable("PERMISSION", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("ROLE", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RouteID");

                    b.Property<short?>("Duration")
                        .HasColumnType("smallint");

                    b.Property<string>("PointOfloading")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PointOFLoading");

                    b.Property<string>("PointOfunloading")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PointOFUnloading");

                    b.HasKey("RouteId");

                    b.ToTable("ROUTE", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NumberPhone")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<bool>("StatusCode")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.GroupDocumenttype", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    b.Property<int>("Document_TypeId")
                        .HasColumnType("int")
                        .HasColumnName("Document_TypeId");

                    b.HasKey("GroupId", "Document_TypeId");

                    b.HasIndex("Document_TypeId");

                    b.ToTable("GroupDocumenttype", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.GroupPermission", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("GroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("GroupPermission", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.UserDocument", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    b.HasKey("UserId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("UserDocument", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.UserFlight", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("FlightId");

                    b.HasKey("UserId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("UserFlight", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroup", (string)null);
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Document", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.Document_Type", "Document_Type")
                        .WithMany("Documents")
                        .HasForeignKey("Document_TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Document_T");

                    b.HasOne("FlightDocSys.Models.Entities.Flight", "Flight")
                        .WithMany("Documents")
                        .HasForeignKey("FlightId")
                        .IsRequired()
                        .HasConstraintName("FK_Document_F");

                    b.Navigation("Document_Type");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Document_Type", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.User", "User")
                        .WithMany("Document_Types")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Document_Type_U");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Flight", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.Route", "Route")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("FK_Flight_R");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.User", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.GroupDocumenttype", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.Document_Type", "Document_Type")
                        .WithMany("GroupDocumenttypes")
                        .HasForeignKey("Document_TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_DOCUMENT_TYPE_GROUP");

                    b.HasOne("FlightDocSys.Models.Entities.Group", "Group")
                        .WithMany("GroupDocumenttypes")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GROUP_DOCUMENT_TYPE");

                    b.Navigation("Document_Type");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.GroupPermission", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.Group", "Group")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GROUP_PERMISSION");

                    b.HasOne("FlightDocSys.Models.Entities.Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_PERMISSION_GROUP");

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.RolePermission", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_PERMISSION_ROLE");

                    b.HasOne("FlightDocSys.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ROLE_PERMISSION");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.UserDocument", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.Document", "Document")
                        .WithMany("UserDocuments")
                        .HasForeignKey("DocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_DOCUMENT_USER");

                    b.HasOne("FlightDocSys.Models.Entities.User", "User")
                        .WithMany("UserDocuments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_DOCUMENT");

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightDocSys.Models.Relation.UserFlight", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.Flight", "Flight")
                        .WithMany("UserFlights")
                        .HasForeignKey("FlightId")
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHT_USER");

                    b.HasOne("FlightDocSys.Models.Entities.User", "User")
                        .WithMany("UserFlights")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_FLIGHT");

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightDocSys.Models.UserGroup", b =>
                {
                    b.HasOne("FlightDocSys.Models.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GROUP_USER");

                    b.HasOne("FlightDocSys.Models.Entities.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_GROUP");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Document", b =>
                {
                    b.Navigation("UserDocuments");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Document_Type", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("GroupDocumenttypes");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Flight", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("UserFlights");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Group", b =>
                {
                    b.Navigation("GroupDocumenttypes");

                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Permission", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.Route", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightDocSys.Models.Entities.User", b =>
                {
                    b.Navigation("Document_Types");

                    b.Navigation("UserDocuments");

                    b.Navigation("UserFlights");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
